# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotcard',
            name='share_id',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
