# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0002_swotcard_share_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotcard',
            name='share_permissions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
